3621 password reset email validation rebased
openlibhums/janeway pull request #4177
Opened 2024-05-13 11:05 UTC by StephDriver

created a new GetResetToken form and linked through to each of the three themes.

Closes https://github.com/BirkbeckCTP/janeway/issues/3621

2024-06-04 09:22 UTC, ajrbyers requested changes
This is a very welcome change. Now that this page is using a Django form we should also display any form errors returned when the form is not valid. This can be done by adding the following include to each of the templates:

`{% include "elements/forms/errors.html" with form=your_form_name_here %}`

2024-06-26 10:03 UTC, StephDriver commented
error validation added and tested.

2024-06-26 14:36 UTC, ajrbyers approved these changes

2024-08-06 16:20 UTC, mauromsl commented on src/core/forms/forms.py
> +class GetResetToken(forms.Form):
Small nitpick, can we add the "Form" suffix to this class name for consistency with the rest of the forms in this module.

2024-08-22 18:30 UTC, mauromsl approved these changes

2024-08-22 18:31 UTC, merged