3097 preprint comment visibility
openlibhums/janeway pull request #4365
Opened 2024-08-16 10:25 UTC by ajrbyers

This PR closes #3097 

- Adds two new settings to control visibility of comment and invited comment features
- Adds a new decorator (with tests) that can check if a repository setting is enabled
- Adds logic to the `repository_preprint` view to block comments when the feature is disabled

Comments block removed:
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/d376b8e0-989c-4f13-a502-21cb27e9ba29">

Manage Reviewers Removed:
<img width="548" alt="image" src="https://github.com/user-attachments/assets/a756509a-6d45-46bd-9b48-9227a50c8039">

Comments Controls Removed:
<img width="308" alt="Screenshot 2024-08-13 at 15 27 24" src="https://github.com/user-attachments/assets/8f44ebbe-564e-48ea-8ea4-a0f8042599b0">

2024-08-19 13:43 UTC, ajrbyers commented
- [ ] Fix conflicts
- [ ] Rebase after https://github.com/BirkbeckCTP/janeway/pull/4368 is merged

2024-12-05 09:29 UTC, mauromsl approved these changes
Lovely work

2024-12-05 09:29 UTC, mauromsl approved these changes

2024-12-06 15:14 UTC, joemull requested changes
I'm getting a migration merge error:

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0045_historicalrepository_display_public_metrics_and_more, 0045_historicalrepository_enable_comments_and_more in repository).
```

2025-02-17 10:00 UTC, joemull reviewed
Waiting to finish reviewing this until https://github.com/openlibhums/janeway/pull/4626 is merged.

2025-03-06 08:30 UTC, joemull commented
Picking up on this @ajrbyers, it has a migration graph error:

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0082_article_abstract_es_article_title_es_section_name_es_and_more, 0084_remove_article_jats_article_type_and_more in submission)
```

But we can now rebase it on master and the migrations should run. I'll then test it and approve it.

2025-03-06 08:30 UTC, joemull requested changes
See comment above on migration graph error; should be possible to fix with rebase.

2025-03-13 09:50 UTC, StephDriver commented
Change required - when comments are disabled, invited comments also do not show. When comments are enabled both comments and invited comments both show. 

Currently 
if comments -> show comments and show invited comments
if not comments -> hide comments and hide invited comments

So the logic of the filters needs to change. 

if comments  -> show comments
if invited comments -> show invited comments

they need to be independent.

2025-03-13 11:00 UTC, StephDriver requested changes
| Comments | Invited comments |  Test Results|
|---|---|---|
|0|0| ✅   |
| 1| 0  |✅  |
|1 | 1 | ✅  |
|0 | 1| :x: |

Text Box to add non-invited comments appears when only invited comments are switched on.  On entering a comment, then a toast appears stating the comment feature is disabled. But only after writing it and clicking to add it.
<img width="198" alt="image" src="https://github.com/user-attachments/assets/a8b237c0-b216-4569-9e3c-3adb22af2518" />

When both sets of comments are off, the comment box does not show at all, and I think that should be the same for all times when non-invited comments are off.

2025-03-13 14:49 UTC, StephDriver approved these changes

2025-03-13 14:52 UTC, StephDriver commented
| Comments | Invited comments |  Test Results|
|---|---|---|
|0|0| ✅   |
| 1| 0  |✅  |
|1 | 1 | ✅  |
|0 | 1| ✅  |

😄

2025-03-14 10:59 UTC, merged