Fixes a bug where submit_info would clear CI.
openlibhums/janeway pull request #4420
Opened 2024-09-24 16:46 UTC by ajrbyers

Pops the CI field out of the `ArticleInfo` form when on submission

2024-09-24 17:55 UTC, mauromsl requested changes

2024-09-24 17:55 UTC, mauromsl commented on src/submission/forms.py
> +        self.fields.pop('competing_interests')
Barbara Liskov wouldn't be proud of this, can we instead not have `competing_interests` on the base form and have a different child when it is needed?

I think what we meant to do here is to create a new `EditArticleMetadata` from that adds whichever fields are needed (in this case `competing_interests`)

```mermaid
classDiagram
    class ArticleInfo {
        <<abstract>>
    }

    class ArticleInfoSubmit {
        
    }
    class EditorArticleInfoSubmit {
        
    }
    class EditArticleMetadata {
competing_interests: String
}

    ArticleInfo <|-- ArticleInfoSubmit
    ArticleInfo <|-- EditorArticleInfoSubmit
    ArticleInfo <|-- EditArticleMetadata
    ```

2024-09-24 19:35 UTC, mauromsl approved these changes

2024-09-25 09:16 UTC, joemull requested changes
These changes seem to make `ArticleInfo` into an abstract base, but we do not explicitly say that anywhere that I can tell. Can we document it as that, so we don't use it by itself anywhere later?

We should also change this test to use the new class, right?

https://github.com/openlibhums/janeway/blob/9051b5f8f3cac907954f0510bafd439e7d397618/src/submission/tests.py#L406-L419

2024-09-25 10:54 UTC, mauromsl commented
> These changes seem to make `ArticleInfo` into an abstract base, but we do not explicitly say that anywhere that I can tell. Can we document it as that, so we don't use it by itself anywhere later?
> 
> We should also change this test to use the new class, right?
> 
> https://github.com/openlibhums/janeway/blob/9051b5f8f3cac907954f0510bafd439e7d397618/src/submission/tests.py#L406-L419
FYI: I don't think we should change the tests, the behaviour is still implemented in `ArticleInfo` and thus, it is the correct class member to run the test on.

The current abstraction is a bit leaky (why does `ArticleInfo` take a special argument called `editor_view` if we already have `EditorArticleInfoSubmit`)

@ajrbyers my suggestion would be to raise a separate issue to fix the abstraction here but for the sake of this feature, don't refactor these forms just yet.

2024-09-25 12:01 UTC, ajrbyers commented
@joemull are you happy with @mauromsl's suggestion above?

2024-09-25 12:10 UTC, joemull commented
> @joemull are you happy with @mauromsl's suggestion above?

Yes, as long as we document it by putting a docstring on the class or opening a new issue.

2024-09-25 12:25 UTC, joemull approved these changes

2024-09-25 12:25 UTC, merged