b #4268 contact forms validate on server not browser
openlibhums/janeway pull request #4456
Opened 2024-10-11 14:14 UTC by StephDriver

closes #4268

2024-10-29 11:24 UTC, ajrbyers requested changes
https://github.com/openlibhums/janeway/issues/4268 talks about page structure as well as the form itself. Can we reduce the scope of 4268 assuming these are covered elsehwere or update the PR to cover these issues?

2024-11-07 08:59 UTC, StephDriver commented
> #4268 talks about page structure as well as the form itself. Can we reduce the scope of 4268 assuming these are covered elsehwere or update the PR to cover these issues?

Looking back, the issue had been reduced to only include Clean theme as the priority work.  I have reviewed it and this fix also addresses material, so I've moved the OLH items (which were the structure ones) to a new issue for fixing later as per the VPAT priorities.

2025-01-08 09:23 UTC, ajrbyers approved these changes
I've added a note about this change in devops (https://github.com/openlibhums/devops/issues/60).

2025-01-09 09:27 UTC, joemull approved these changes

2025-01-09 09:27 UTC, merged