Adjust a few dependencies for Python 3.12 on Mac
openlibhums/janeway pull request #4460
Opened 2024-10-18 11:11 UTC by joemull

2024-11-05 11:26 UTC, ajrbyers requested changes

2024-11-05 11:26 UTC, ajrbyers commented on requirements.txt
> +pytz
Should we pin a pytz version? There is a PR in 1.7.x that also adds pytz with 2014.1 pinned.

https://github.com/openlibhums/janeway/pull/4468/files

2024-12-05 15:47 UTC, ajrbyers approved these changes

2025-01-14 10:36 UTC, mauromsl approved these changes

2025-01-14 10:36 UTC, merged