#3965 adds text to the move_to_next modal.
openlibhums/janeway pull request #4472
Opened 2024-10-29 13:23 UTC by ajrbyers

- Adds text to explain the current stage and the stage the article will move to.

<img width="587" alt="Screenshot 2024-10-29 at 13 23 08" src="https://github.com/user-attachments/assets/b671d679-24e6-4e33-a222-b21bba603be2">

2024-12-05 15:59 UTC, Astronaut-resting approved these changes
Better!

2024-12-06 09:29 UTC, StephDriver approved these changes
really like this - far clearer.

2024-12-06 09:32 UTC, StephDriver requested changes
much clearer, but I think the button text should also update to reflect this.  Instead of move to next stage, a move to `name of next stage` and likewise keep in `name of current stage`

also link to which issue is being closed.

2025-01-10 08:27 UTC, StephDriver approved these changes

2025-01-15 09:19 UTC, merged

2025-01-15 09:47 UTC, joemull commented
@ajrbyers FYI I was planning to review this one since Steph asked me to. She wasn't able to test it out and there is no screenshot here so I was going to test it today.