Fixed an issue where html tags where being displayed on news item titles
openlibhums/janeway pull request #4475
Opened 2024-10-31 17:34 UTC by mauromsl

closes #4467

2024-11-04 10:21 UTC, ajrbyers requested changes

2024-11-04 10:21 UTC, ajrbyers commented on src/themes/OLH/templates/journal/homepage_elements/news.html
> +                                    alt="{{ item.title|safe }}"/></a>
Should we use striptags here? Tags are not valid inside an alt attribute.

2024-11-04 10:21 UTC, ajrbyers commented on src/themes/material/templates/journal/homepage_elements/news.html
> +                                     alt="{{ item.title|safe }}"/>
Should we use striptags here? Tags are not valid inside an alt attribute.

2024-11-05 09:59 UTC, ajrbyers approved these changes

2024-11-05 16:02 UTC, StephDriver requested changes
The italics seem fine, but I don't think strip tags is sorting out the ampersand issue within the alt

<img width="439" alt="image" src="https://github.com/user-attachments/assets/156207a0-910d-42c2-bf76-34549d7fdeaf">

<img width="453" alt="image" src="https://github.com/user-attachments/assets/7d0c2b28-adcc-4e4f-a190-0972531645b4">

2024-11-05 17:00 UTC, ajrbyers approved these changes

2024-11-05 17:00 UTC, merged