icons identified #4215
openlibhums/janeway pull request #4492
Opened 2024-11-18 16:43 UTC by StephDriver

closes #4215

2024-11-25 10:46 UTC, StephDriver commented
Note, while an aria-label on an `<a>` should mean that everything inside, including any icons, are then hidden as the label takes precedence, SiteImprove has been flagging up internal elements as not being accessible despite this... so in a belt and braces approach I have marked internal icons as hidden regardless of aria label.

2024-11-25 12:04 UTC, StephDriver commented
I have set this up so that there are comments in the code explaining the updates, which I then removed before testing.  So to see the reason behind a change, please look back at [Commit](https://github.com/openlibhums/janeway/tree/68b5e12998a2910552ca5dd04815cfbc1f3bcafd)

2024-11-25 12:27 UTC, StephDriver commented
Work remaining:
- [ ] update translations 
- [ ] test every template which has been touched by this.

2024-11-28 12:06 UTC, StephDriver commented
There are 5 kinds of icon use found - and therefore 5 different syntax.

- Decorative - these icons are purely decorative, and should include `aria-hidden="true"`
- Decorative Date - these icons are used to indicate a date, and should be marked as with decorative, and the date should itself be marked up with the `<time> ` html tag.
- Semantic - these icons should be hidden with decorative, but have adjacent `<span class="sr-only"> text alternative</span>
- Semantic Image - these are using image markup, and so there should be alternative text as appropriate for images.
- Semantic Link - here the icon is part of the `<a>` html tag and there should be an appropriate `aria-label` on the link so that the purpose of the link is avaliable regardless of icon visibility.

2024-12-05 10:24 UTC, StephDriver commented
- [ ] NB. Waiting on the translation PR before can finish this.  Will then need to rebase and follow new translations procedure.

2024-12-09 09:27 UTC, StephDriver commented
Testing

| Theme | Template | URL | Tested |
|---|---|---|---|
| Clean | core/homepage_elements/search_bar.html|  |  |
| Clean | core/news/item.html|  |  |
| Clean | elements/article_listing.html|  |  |
| Clean | elements/preprint_block.html|  |  |
| Clean | elements/public_reviews.html|  |  |
| Clean | elements/sections_block.html|  |  |
| Clean | elements/journal/editorial_social_content.html|  |  |
| Clean | elements/journal/issue_sidebar.html|  |  |
| Clean | journal/article.html|  |  |
| Clean | journal/print.html|  |  |
| Clean | journal/homepage_elements/carousel.html|  |  |
| Clean | press/nav.html|  |  |
| Clean | press/core/news/item.html|  |  |
| Material | core/nav.html|  |  |
| Material | core/news/item.html|  |  |
| Material | elements/article_listing.html|  |  |
| Material | elements/license_block.html|  |  |
| Material | elements/preprint_block.html|  |  |
| Material | elements/public_reviews.html|  |  |
| Material | elements/journal/issue_list.html|  |  |
| Material | elements/journal/issue_sidebar.html|  |  |
| Material | journal/article.html|  |  |
| Material | preprints/article.html|  |  |
| Material | preprints/editors.html|  |  |
| Material | preprints/list.html|  |  |
| Material | press/core/news/item.html|  |  |
| Material | repository/preprint.html|  |  |
| OLH | core/base.html|  |  |
| OLH | core/nav.html|  |  |
| OLH | core/homepage_elements/search_bar.html|  |  |
| OLH | core/news/item.html|  |  |
| OLH | elements/public_reviews.html|  |  |
| OLH | elements/section_block.html|  |  |
| OLH | elements/journal/box_article.html|  |  |
| OLH | elements/journal/editorial_social_content.html|  |  |
| OLH | elements/journal/issue_sidebar.html|  |  |
| OLH | elements/journal/preprint_article_listing.html|  |  |
| OLH | elements/submit/author.html|  |  |
| OLH | journal/article.html|  |  |
| OLH | journal/print.html|  |  |
| OLH | press/core/news/item.html|  |  |
| OLH | repository/home.html|  |  |
| OLH | repository/list.html|  |  |
| OLH | repository/preprint.html|  |  |
| OLH | repository/elements/preprint_home_listing.html|  |  |

2024-12-16 14:46 UTC, StephDriver commented
@ajrbyers this draft is now done other than for the testing of the remaining templates as above.

2024-12-17 17:59 UTC, StephDriver commented
NOTE, now found 31 other icons from the material set, updating these...

to do
- [ ] update material icons to consistent with above categories (and so only one font set used)
- [ ] update list of templates to test
- [ ] retest templates as required
- [ ] then... can move on to hunt for remaining elusive templates.

2024-12-19 15:24 UTC, StephDriver commented
# Testing

## Results

| Theme    | Template                                       | Tested                           |
| -------- | ---------------------------------------------- | -------------------------------- |
| Clean    | core/homepage_elements/search_bar.html         | :white_check_mark:               |
| Clean    | core/news/item.html                            | :white_check_mark:               |
| Clean    | elements/article_listing.html                  | :white_check_mark:               |
| Clean    | elements/journal/editorial_social_content.html | :white_check_mark:               |
| Clean    | elements/journal/issue_sidebar.html            | :white_check_mark:               |
| Clean    | elements/preprint_block.html                   | passed on sight                  |
| Clean    | elements/public_reviews.html                   | passed on sight                  |
| Clean    | elements/sections_block.html                   | :white_check_mark:               |
| Clean    | journal/article.html                           | :white_check_mark:               |
| Clean    | journal/homepage_elements/carousel.html        | :white_check_mark:               |
| Clean    | journal/print.html                             | no styling on page, remove this. |
| Clean    | press/core/news/item.html                      | passed on sight                  |
| Clean    | press/nav.html                                 | :white_check_mark:               |
| Material | core/homepage_elements/search_bar.html         | :white_check_mark:               |
| Material | core/nav.html                                  | :white_check_mark:               |
| Material | core/news/item.html                            | :white_check_mark:               |
| Material | elements/article_listing.html                  | :white_check_mark:               |
| Material | elements/journal/issue_list.html               | :white_check_mark:               |
| Material | elements/journal/issue_sidebar.html            | :white_check_mark:               |
| Material | elements/license_block.html                    | :white_check_mark:               |
| Material | elements/nav_element.html                      | not used                         |
| Material | elements/pagination.html                       | :white_check_mark:               |
| Material | elements/preprint_block.html                   | passed on sight                  |
| Material | elements/public_reviews.html                   | passed on sight                  |
| Material | elements/sections_display.html                 | :white_check_mark:               |
| Material | journal/article.html                           | :white_check_mark:               |
| Material | preprints/article.html                         | not used                         |
| Material | preprints/editors.html                         | passed on sight                  |
| Material | preprints/list.html                            | deprecated                       |
| Material | press/core/news/item.html                      | passed on sight                  |
| Material | press/nav.html                                 | :white_check_mark:               |
| Material | repository/home.html                           | :white_check_mark:               |
| Material | repository/list.html                           | :white_check_mark:               |
| Material | repository/nav.html                            | :white_check_mark:               |
| Material | repository/preprint.html                       | :white_check_mark:               |
| OLH      | core/base.html                                 | :white_check_mark:               |
| OLH      | core/homepage_elements/search_bar.html         | :white_check_mark:               |
| OLH      | core/nav.html                                  | :white_check_mark:               |
| OLH      | core/news/item.html                            | :white_check_mark:               |
| OLH      | elements/journal/box_article.html              | :white_check_mark:               |
| OLH      | elements/journal/editorial_social_content.html | :white_check_mark:               |
| OLH      | elements/journal/issue_sidebar.html            | :white_check_mark:               |
| OLH      | elements/journal/preprint_article_listing.html | not used                         |
| OLH      | elements/public_reviews.html                   | passed on sight                  |
| OLH      | elements/section_block.html                    | :white_check_mark:               |
| OLH      | elements/submit/author.html                    | not used                         |
| OLH      | journal/article.html                           | :white_check_mark:               |
| OLH      | journal/print.html                             | no styling on page, remove this. |
| OLH      | press/core/news/item.html                      | passed on sight                  |
| OLH      | repository/elements/preprint_home_listing.html | :white_check_mark:               |
| OLH      | repository/home.html                           | :white_check_mark:               |
| OLH      | repository/list.html                           | :white_check_mark:               |
| OLH      | repository/preprint.html                       | :white_check_mark:               |

## Notes

- "passed on sight" are items where code was reviewed by @ajrbyers 
- ✅ passed a manual review of the page 
- "not used" / "deprecated" are templates no longer in use
- "no styling on page" refers to two templates were icons shouldn't be used anyway, these were then removed.

2025-02-11 11:54 UTC, ajrbyers commented
I've re-assigned this issue to @StephDriver as there is an outstanding conflict.

2025-02-14 09:01 UTC, StephDriver commented
> I've re-assigned this issue to @StephDriver as there is an outstanding conflict.

resolved.

2025-03-03 12:47 UTC, StephDriver commented
conflicts resolved.

2025-03-04 10:54 UTC, joemull requested changes
Amazing work!

I caught one typo with missing end `</span>`.

I also wanted to request that we go ahead and use accessible form `label` elements for the search inputs that have until now been "labelled" by means of search icons. Please see comments inline about that. Is that acceptable in this PR or do you prefer to handle it separately along with accessible names for other form inputs?

2025-03-04 10:54 UTC, joemull commented on src/themes/OLH/templates/core/base.html
>                                  <input type="hidden" name="sort" value="title">
This search input is still missing an accessible name. The placeholder is not enough because it goes away once the user types something. Can we add an sr-only `label` with a value of "Search" and tie it to the input?

```html
<span class="input-group-label"><i aria-hidden="true" class="fa fa-search"></i></span>
<label class="sr-only" for="article_search">{% trans "Search" %}</label>
<input class="input-group-field" type="search" name="article_search" id="article_search" placeholder="{% trans 'Search' %}">
```

2025-03-04 10:54 UTC, joemull commented on src/themes/OLH/templates/core/homepage_elements/search_bar.html
>                <input name="article_search" class="input-group-field" type="text">
Similar to with the OLH theme template for search, this needs a more robust label explicitly tied to the input. In this case I think the `<span class="sr-only">` should be changed to a `label` and tied to the input with a "for" attribute.

2025-03-04 10:54 UTC, joemull commented on src/themes/OLH/templates/repository/home.html
>                                     placeholder="Search {{ request.repository.object_name_plural }}...">
This needs an accessible label like the other two search bars above.

In this case a `label` with sr-only and a for linked to the search input should do the trick.

2025-03-04 10:54 UTC, joemull commented on src/themes/OLH/templates/repository/list.html
>                                         {% if search_term %}value="{{ search_term }}"{% endif %}>
As above, use `label` instead of `span` for the sr-only line, and connect it to the search input with `for`

2025-03-04 10:54 UTC, joemull commented on src/themes/material/templates/elements/journal/issue_list.html
> +                        <span class="sr-only">{% trans 'Close.' %}</span>
Missing an end tag for the `span class="card-title ..."`?

2025-03-06 08:52 UTC, StephDriver commented on src/themes/OLH/templates/core/base.html
>                                  <input type="hidden" name="sort" value="title">
this is no more inaccessible than before, this change was just about icons.

2025-03-06 08:53 UTC, StephDriver commented on src/themes/OLH/templates/repository/home.html
>                                     placeholder="Search {{ request.repository.object_name_plural }}...">
yes, but not in this PR.

2025-03-06 08:53 UTC, StephDriver commented on src/themes/OLH/templates/repository/list.html
>                                         {% if search_term %}value="{{ search_term }}"{% endif %}>
yes, but not here.

2025-03-06 09:17 UTC, joemull approved these changes

2025-03-11 12:24 UTC, mauromsl approved these changes

2025-03-11 12:28 UTC, merged